### ISSUE TITLE
compile error on Unity2019.4.19f1

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [NewBloodInteractive/com.newblood.lightdata#1]
invalid param type at SceneObjectIdentifier.GetSceneObjectIdentifierSlow()

**Comment by DaZombieKiller** [comment]
Could you provide the full error message including the line and column information?

**Comment by DaZombieKiller** [comment]
On further investigation, the overloads of the `GlobalObjectId` methods taking instance IDs were added in Unity 2020.1, so they needed to be `#if`'d out with `UNITY_2020_1_OR_NEWER`. Fixed in https://github.com/NewBloodInteractive/com.newblood.lightdata/commit/37ec3efebc66f40afa62b3adc18f99c1c00e55d0.
